### ISSUE TITLE
实验数据集

### ISSUE THREAD

**Issue by sienna-wxy** [zhangjiatao/GMUC#1]
您好，请问构造NL27K-N1/N2/N3时对加入负样本的confidence的计算代码可以公开吗？
参考了CKRL那篇文章，其中Local Triple Confidence部分的计算随着模型训练是更新的，想请教下这部分是如何处理的。
打扰了，谢谢~

**Comment by zhangjiatao** [comment]
Hello,
The code for confidence computing is public which you can find in https://github.com/zhangjiatao/Confidence-Knowledge-Graph.
For your second question, our solution is simply fix the trainning epoch of CKRL.
Best Wishes.

**Comment by zhangjiatao** [comment]
> 您好，请问构造NL27K-N1/N2/N3时对加入负样本的confidence的计算代码可以公开吗？ 参考了CKRL那篇文章，其中Local Triple Confidence部分的计算随着模型训练是更新的，想请教下这部分是如何处理的。 打扰了，谢谢~

Hello,
The code for confidence computing is public which you can find in https://github.com/zhangjiatao/Confidence-Knowledge-Graph.
For your second question, our solution is simply fix the trainning epoch of CKRL.
Best Wishes.
